/**
 * openapi/response-map.ts — 端点 → contract 响应 schema 映射。
 *
 * defineRoute 不带响应 schema（响应壳由 envelope 统一保证），逐端点的响应形状住在这里。
 * 键 = `${METHOD} ${完整路径}`（Express 风格 :id，与 discover.ts 产出一致）。
 * 映射只引用 packages/studio-contract 已导出的 xxxResponseSchema——schema 正本在 contract，
 * 本文件只做「端点 ↔ schema」装订。未映射端点在文档中退化为通用 { data } 壳（如实标注）。
 *
 * 防漂移：openapi 测试断言「映射键 ⊆ 实际发现的端点」——路由改名/删除即测试红。
 */

import type { z } from 'zod';
import {
  // workunit
  workUnitListResponseSchema,
  workUnitResponseSchema,
  lastDoneResponseSchema,
  changedFilesResponseSchema,
  treeTokenReportResponseSchema,
  verifyResultResponseSchema,
  dispatchReviewResponseSchema,
  adoptOpportunityResponseSchema,
  ignoreOpportunityResponseSchema,
  discussionMessagesResponseSchema,
  discussionMessageResponseSchema,
  // channels
  channelListResponseSchema,
  channelResponseSchema,
  channelCurrentPmoResponseSchema,
  channelPmoCandidatesResponseSchema,
  channelSuggestionsResponseSchema,
  mergeTargetResponseSchema,
  channelMessagesResponseSchema,
  channelMessageResponseSchema,
  channelFileVocabularyResponseSchema,
  savedImageResponseSchema,
  deleteChannelResponseSchema,
  archiveChannelResponseSchema,
  restoreChannelResponseSchema,
  updateMembersResponseSchema,
  convertToTaskResponseSchema,
  convertSuggestionResponseSchema,
  // requirements
  requirementListResponseSchema,
  requirementResponseSchema,
  requirementChainResponseSchema,
  chainStatsResponseSchema,
  // pmo
  projectListResponseSchema,
  projectResponseSchema,
  deliveryStatusResponseSchema,
  deliverResultResponseSchema,
  markDeliveredResultResponseSchema,
  publishProjectResultResponseSchema,
  linkedSddsResponseSchema,
  parsePmoCommandResultResponseSchema,
  deleteProjectResultResponseSchema,
  okrListResponseSchema,
  okrDetailResponseSchema,
  okrMutationResultResponseSchema,
  deleteOkrResultResponseSchema,
  // companies / projects / workspaces
  companyListResponseSchema,
  companyResponseSchema,
  companySizeConfigResponseSchema,
  companyHallStatsResponseSchema,
  localProjectListResponseSchema,
  projectExcludeResponseSchema,
  workspaceListResponseSchema,
  workspaceResponseSchema,
  workspaceRuntimeListResponseSchema,
  workspaceRuntimesResponseSchema,
  deleteWorkspaceResponseSchema,
  // skills
  skillListResponseSchema,
  skillDiscoverResponseSchema,
  skillManifestResponseSchema,
  skillDetailResponseSchema,
  skillResponseSchema,
  deleteSkillResponseSchema,
  skillsStatsResponseSchema,
  demotionProposalListResponseSchema,
  reviewDemotionResponseSchema,
  skillProposalListResponseSchema,
  scanSkillProposalsResponseSchema,
  extractSkillProposalResponseSchema,
  retractSkillResponseSchema,
  // specs
  analyzeChangeResponseSchema,
  changeRecordResponseSchema,
  validateChangeResponseSchema,
  gatePolicyResponseSchema,
  gatePolicyMapResponseSchema,
  specChangeListResponseSchema,
  changeStatsResponseSchema,
  importChangesResponseSchema,
  // triggers / evolution
  listTriggersResponseSchema,
  triggerCostsResponseSchema,
  triggerResponseSchema,
  saveTriggerResponseSchema,
  fireTriggerResponseSchema,
  deleteTriggerResponseSchema,
  triggerLogsResponseSchema,
  triggerStatusResponseSchema,
  evolutionProposalListResponseSchema,
  evolutionProposalResponseSchema,
  evolutionRunResponseSchema,
  // knowledge（/knowledge + /knowledge-service + /api/knowledge 内部）
  requirementDocListResponseSchema,
  readKnowledgeFileResponseSchema,
  knowledgeFileResponseSchema,
  knowledgeAskResponseSchema,
  knowledgeGapsResponseSchema,
  knowledgeGapStatsResponseSchema,
  unifiedKnowledgeListResponseSchema,
  createUnifiedEntryResponseSchema,
  resolutionListResponseSchema,
  knowledgeSearchResponseSchema,
  resolutionDensityResponseSchema,
  crossSessionStatsResponseSchema,
  knowledgeSyncStatusResponseSchema,
  upsertKnowledgeResponseSchema,
  knowledgeMaintenanceResponseSchema,
  knowledgeServiceStatsResponseSchema,
  knowledgeServiceSearchResponseSchema,
  knowledgeEntryListResponseSchema,
  knowledgeEntryResponseSchema,
  createKnowledgeEntryResponseSchema,
  knowledgeHealthResponseSchema,
  knowledgeFlywheelResponseSchema,
  knowledgeAuditResponseSchema,
  analystAccuracyResponseSchema,
  injectContextResponseSchema,
  matchResolutionsResponseSchema,
  knowledgeSuccessResponseSchema,
  // review-proposals / action-center / library / events / transcripts / monitoring
  reviewProposalApproveResponseSchema,
  reviewProposalRejectResponseSchema,
  reviewProposalStatusResponseSchema,
  actionCenterResponseSchema,
  libraryListResponseSchema,
  libraryDocDetailResponseSchema,
  createStudioEventResponseSchema,
  eventSearchResponseSchema,
  ingestAgentEventsResponseSchema,
  transcriptResponseSchema,
  agentSummaryResponseSchema,
  monitoringStatsResponseSchema,
  flywheelStatsResponseSchema,
  overheadStatsResponseSchema,
  overviewMetricsResponseSchema,
  efficiencyMetricsResponseSchema,
  // notifications / notify-channels / outbound-notify
  notificationListResponseSchema,
  unreadCountResponseSchema,
  notificationReadResponseSchema,
  notifyChannelsStateResponseSchema,
  wecomChannelStateResponseSchema,
  clawbotBindStartResponseSchema,
  clawbotBindStatusResponseSchema,
  notifyChannelsSuccessResponseSchema,
  notifySendResponseSchema,
  // auth / audit-logs / admin
  authStatusResponseSchema,
  authResultResponseSchema,
  authMeResponseSchema,
  authRefreshResponseSchema,
  logoutResponseSchema,
  cleanupResponseSchema,
  auditLogListResponseSchema,
  auditLogStatsResponseSchema,
  auditLogActionsResponseSchema,
  auditLogResourcesResponseSchema,
  auditLogGetResponseSchema,
  docsFreshnessResponseSchema,
  // harness / cso / iron-laws
  traceListResponseSchema,
  traceRecordResponseSchema,
  traceAnalysisResponseSchema,
  traceAnomaliesResponseSchema,
  constraintListResponseSchema,
  constraintStatsResponseSchema,
  retiredConstraintListResponseSchema,
  constraintGetResponseSchema,
  proposeUpgradeResponseSchema,
  rollbackConstraintResponseSchema,
  checkConstraintsResponseSchema,
  harnessKnowledgeQueryResponseSchema,
  harnessKnowledgeListResponseSchema,
  harnessKnowledgeGetResponseSchema,
  harnessKnowledgeSaveResponseSchema,
  harnessKnowledgeDeleteResponseSchema,
  harnessKnowledgeLintResponseSchema,
  estimateTokensResponseSchema,
  sessionCreateResponseSchema,
  sessionEventResponseSchema,
  sessionGetResponseSchema,
  sessionCheckpointResponseSchema,
  harnessAgentStateResponseSchema,
  harnessAgentListResponseSchema,
  classifyResponseSchema,
  failureRecordResponseSchema,
  harnessHealthResponseSchema,
  csoValidateResponseSchema,
  ironLawListResponseSchema,
  ironLawGetResponseSchema,
  ironLawCheckResponseSchema,
  ironLawCheckAllResponseSchema,
  // mcp / builtin-tools / executions / agents / agent-profiles
  mcpToolListResponseSchema,
  mcpToolCallResponseSchema,
  mcpHealthResponseSchema,
  mcpAdminToolListResponseSchema,
  mcpToolToggleResponseSchema,
  mcpAdminStatsResponseSchema,
  mcpRolePermissionsResponseSchema,
  mcpPermissionSetResponseSchema,
  mcpAuditResponseSchema,
  builtinToolListResponseSchema,
  builtinToolGetResponseSchema,
  builtinToolPatchResponseSchema,
  executionListResponseSchema,
  executionGetResponseSchema,
  executionEventResponseSchema,
  legacyAgentListResponseSchema,
  legacyAgentResponseSchema,
  agentTokenUsageResponseSchema,
  agentProfileListResponseSchema,
  agentProfileResponseSchema,
  rolePresetListResponseSchema,
  agentInstanceListResponseSchema,
  agentInstanceResponseSchema,
  // lark / dingtalk health
  larkHealthResponseSchema,
  dingtalkHealthResponseSchema,
} from '@dommaker/studio-contract';

export interface ResponseDoc {
  /** 成功响应 schema（contract 导出，已含 { data } 壳）；缺省 = 文档退化为通用壳 */
  response?: z.ZodTypeAny;
  /** 操作摘要（缺省 = METHOD PATH 机械摘要） */
  summary?: string;
  /** 附加说明（并入 operation.description） */
  description?: string;
}

export const RESPONSE_MAP: Record<string, ResponseDoc> = {
  // ── workunit ──
  'GET /api/v1/workunits': { response: workUnitListResponseSchema, summary: 'WorkUnit 列表（分页，#109 附 claimable）' },
  'POST /api/v1/workunits': { response: workUnitResponseSchema, summary: '创建 WorkUnit' },
  'GET /api/v1/workunits/last-done': { response: lastDoneResponseSchema, summary: '批量最近完成（每 assignee 一条）' },
  'GET /api/v1/workunits/changed-files': { response: changedFilesResponseSchema, summary: '批量 WU 变更文件映射' },
  'GET /api/v1/workunits/:id': { response: workUnitResponseSchema, summary: 'WorkUnit 详情' },
  'PUT /api/v1/workunits/:id': { response: workUnitResponseSchema, summary: '更新 WorkUnit（全可选补丁）' },
  'POST /api/v1/workunits/from-message': { response: workUnitResponseSchema, summary: '频道消息涌现建单' },
  'POST /api/v1/workunits/:id/claim': { response: workUnitResponseSchema, summary: '认领（flock 悲观互斥）' },
  'POST /api/v1/workunits/:id/unclaim': { response: workUnitResponseSchema, summary: '取消认领' },
  'POST /api/v1/workunits/:id/status': { response: workUnitResponseSchema, summary: '状态机流转（human-only）' },
  'POST /api/v1/workunits/:id/review-passed': { response: workUnitResponseSchema, summary: '评审通过（in_review → done）' },
  'POST /api/v1/workunits/:id/review-rejected': { response: workUnitResponseSchema, summary: '评审打回' },
  'POST /api/v1/workunits/:id/verify': { response: verifyResultResponseSchema, summary: '人工重跑 L1 自动验证（human-only）' },
  'POST /api/v1/workunits/:id/dispatch-review': { response: dispatchReviewResponseSchema, summary: '人工补派 agent 评审（human-only）' },
  'POST /api/v1/workunits/:id/resume': { response: workUnitResponseSchema, summary: '继续执行（Web 按钮通道）' },
  'POST /api/v1/workunits/:id/close': { response: workUnitResponseSchema, summary: '关闭任务（死信显式关闭）' },
  'POST /api/v1/workunits/:id/ruling': { response: workUnitResponseSchema, summary: '裁决轮一次性提交（#467）' },
  'POST /api/v1/workunits/:id/direction': { response: workUnitResponseSchema, summary: '方向锁定提交（#567）' },
  'POST /api/v1/workunits/:id/opportunities/:oppId/adopt': { response: adoptOpportunityResponseSchema, summary: '巡检机会采纳（建 feature 子单）' },
  'POST /api/v1/workunits/:id/opportunities/:oppId/ignore': { response: ignoreOpportunityResponseSchema, summary: '巡检机会忽略（终态）' },
  'GET /api/v1/workunits/:id/messages': { response: discussionMessagesResponseSchema, summary: '讨论区消息列表（cursor 分页）' },
  'POST /api/v1/workunits/:id/messages': { response: discussionMessageResponseSchema, summary: '讨论区发消息' },
  'PATCH /api/v1/workunits/:id/messages/:messageId': { response: discussionMessageResponseSchema, summary: '编辑讨论区消息' },
  'GET /api/v1/workunits/:id/tree-tokens': { response: treeTokenReportResponseSchema, summary: '树级 token 开销报告' },

  // ── channels ──
  'GET /api/v1/channels': { response: channelListResponseSchema, summary: '频道列表' },
  'POST /api/v1/channels': { response: channelResponseSchema, summary: '创建频道' },
  'GET /api/v1/channels/:id': { response: channelResponseSchema, summary: '频道详情' },
  'PATCH /api/v1/channels/:id': { response: channelResponseSchema, summary: '更新频道' },
  'DELETE /api/v1/channels/:id': { response: deleteChannelResponseSchema, summary: '删除频道' },
  'PUT /api/v1/channels/:id/archive': { response: archiveChannelResponseSchema, summary: '归档频道' },
  'PUT /api/v1/channels/:id/restore': { response: restoreChannelResponseSchema, summary: '恢复频道' },
  'PATCH /api/v1/channels/:id/members': { response: updateMembersResponseSchema, summary: '更新频道成员' },
  'GET /api/v1/channels/:id/messages': { response: channelMessagesResponseSchema, summary: '频道消息列表（cursor 分页）' },
  'POST /api/v1/channels/:id/messages': { response: channelMessageResponseSchema, summary: '发频道消息（含 @mention 派单）' },
  'GET /api/v1/channels/:id/current-pmo': { response: channelCurrentPmoResponseSchema, summary: '当前 PMO 派生' },
  'GET /api/v1/channels/:id/pmo-candidates': { response: channelPmoCandidatesResponseSchema, summary: 'PMO 候选列表' },
  'GET /api/v1/channels/:id/suggestions': { response: channelSuggestionsResponseSchema, summary: '情境引导建议' },
  'GET /api/v1/channels/:id/merge-target': { response: mergeTargetResponseSchema, summary: '合并目标推导（#632）' },
  'GET /api/v1/channels/:id/file-vocabulary': { response: channelFileVocabularyResponseSchema, summary: '@文件引用词表' },
  'POST /api/v1/channels/:id/messages/:messageId/convert-to-task': { response: convertToTaskResponseSchema, summary: '消息转任务' },
  'POST /api/v1/channels/:id/messages/:messageId/convert-to-task/suggest': { response: convertSuggestionResponseSchema, summary: '消息转任务建议' },
  'POST /api/v1/channels/:id/attachments': { response: savedImageResponseSchema, summary: '上传图片附件（base64）' },

  // ── requirements ──
  'GET /api/v1/requirements': { response: requirementListResponseSchema, summary: 'REQ 列表' },
  'POST /api/v1/requirements': { response: requirementResponseSchema, summary: '创建 REQ' },
  'GET /api/v1/requirements/:id': { response: requirementResponseSchema, summary: 'REQ 详情' },
  'PATCH /api/v1/requirements/:id': { response: requirementResponseSchema, summary: '更新 REQ' },
  'GET /api/v1/requirements/:id/chain': { response: requirementChainResponseSchema, summary: 'REQ 全链路（需求→WU→产物）' },
  'GET /api/v1/requirements/chain-stats': { response: chainStatsResponseSchema, summary: '链路统计' },

  // ── pmo ──
  'GET /api/v1/pmo/project': { response: projectListResponseSchema, summary: '项目列表' },
  'POST /api/v1/pmo/project': { response: projectResponseSchema, summary: '创建项目' },
  'GET /api/v1/pmo/project/:id': { response: projectResponseSchema, summary: '项目详情' },
  'PUT /api/v1/pmo/project/:id': { response: projectResponseSchema, summary: '更新项目' },
  'PUT /api/v1/pmo/project/:id/status': { response: projectResponseSchema, summary: '更新项目状态' },
  'DELETE /api/v1/pmo/project/:id': { response: deleteProjectResultResponseSchema, summary: '删除项目' },
  'GET /api/v1/pmo/project/by-pmo/:pmoNumber': { response: projectResponseSchema, summary: '按 PMO 编号查项目' },
  'GET /api/v1/pmo/project/:id/delivery': { response: deliveryStatusResponseSchema, summary: '交付状态（证据台账）' },
  'POST /api/v1/pmo/project/:id/deliver': { response: deliverResultResponseSchema, summary: '交付守卫执行', description: '409 为错误壳扩展 { error: { code, message, missing?, conflictFiles? } }' },
  'POST /api/v1/pmo/project/:id/mark-delivered': { response: markDeliveredResultResponseSchema, summary: '标记已交付' },
  'POST /api/v1/pmo/project/:id/publish': { response: publishProjectResultResponseSchema, summary: '发布项目' },
  'GET /api/v1/pmo/project/:id/sdd': { response: linkedSddsResponseSchema, summary: '项目关联 SDD' },
  'POST /api/v1/pmo/project/parse-command': { response: parsePmoCommandResultResponseSchema, summary: 'PMO 指令解析' },
  'GET /api/v1/pmo/okr': { response: okrListResponseSchema, summary: 'OKR 列表' },
  'POST /api/v1/pmo/okr': { response: okrMutationResultResponseSchema, summary: '创建 OKR' },
  'GET /api/v1/pmo/okr/:id': { response: okrDetailResponseSchema, summary: 'OKR 详情' },
  'PUT /api/v1/pmo/okr/:id': { response: okrMutationResultResponseSchema, summary: '更新 OKR' },
  'DELETE /api/v1/pmo/okr/:id': { response: deleteOkrResultResponseSchema, summary: '删除 OKR' },

  // ── companies / projects / workspaces ──
  'GET /api/v1/companies': { response: companyListResponseSchema, summary: '公司列表' },
  'POST /api/v1/companies': { response: companyResponseSchema, summary: '创建公司' },
  'GET /api/v1/companies/:companyId': { response: companyResponseSchema, summary: '公司详情' },
  'PATCH /api/v1/companies/:companyId': { response: companyResponseSchema, summary: '更新公司' },
  'GET /api/v1/companies/sizes/config': { response: companySizeConfigResponseSchema, summary: '公司规模配置' },
  'GET /api/v1/companies/:companyId/hall-stats': { response: companyHallStatsResponseSchema, summary: '大厅统计' },
  'GET /api/v1/projects/discover': { response: localProjectListResponseSchema, summary: '本机工程发现' },
  'GET /api/v1/projects/exclude': { response: projectExcludeResponseSchema, summary: '工程排除清单' },
  'PUT /api/v1/projects/exclude': { response: projectExcludeResponseSchema, summary: '更新排除清单' },
  'GET /api/v1/workspaces': { response: workspaceListResponseSchema, summary: 'Workspace 列表' },
  'GET /api/v1/workspaces/:id': { response: workspaceResponseSchema, summary: 'Workspace 详情' },
  'GET /api/v1/workspaces/runtimes': { response: workspaceRuntimesResponseSchema, summary: '全部运行时清单' },
  'GET /api/v1/workspaces/:id/runtimes': { response: workspaceRuntimeListResponseSchema, summary: 'Workspace 运行时清单' },
  'DELETE /api/v1/workspaces/:id': { response: deleteWorkspaceResponseSchema, summary: '删除 Workspace' },

  // ── skills ──
  'GET /api/v1/skills': { response: skillListResponseSchema, summary: '技能列表（分页）' },
  'POST /api/v1/skills': { response: skillResponseSchema, summary: '创建技能' },
  'GET /api/v1/skills/:id': { response: skillDetailResponseSchema, summary: '技能详情' },
  'PATCH /api/v1/skills/:id': { response: skillResponseSchema, summary: '更新技能' },
  'DELETE /api/v1/skills/:id': { response: deleteSkillResponseSchema, summary: '删除技能' },
  'GET /api/v1/skills/discover': { response: skillDiscoverResponseSchema, summary: '技能发现' },
  'GET /api/v1/skills/manifest': { response: skillManifestResponseSchema, summary: '技能清单' },
  'GET /api/v1/skills/stats': { response: skillsStatsResponseSchema, summary: '技能统计', description: '历史注册顺序被 GET /:id 遮蔽（registry 注释在案）' },
  'POST /api/v1/skills/:id/publish': { response: skillResponseSchema, summary: '发布技能（promote 门禁；拒绝体为错误壳扩展 { error: { code, message, reasons } }）' },
  'POST /api/v1/skills/:id/deprecate': { response: skillResponseSchema, summary: '弃用技能' },
  'POST /api/v1/skills/:id/restore': { response: skillResponseSchema, summary: '恢复技能' },
  'POST /api/v1/skills/:id/usage': { response: skillResponseSchema, summary: '记录技能使用' },
  'POST /api/v1/skills/:id/retract/decide': { response: skillResponseSchema, summary: '撤回裁决' },
  'GET /api/v1/skills/demotion-proposals': { response: demotionProposalListResponseSchema, summary: '降级提案列表' },
  'POST /api/v1/skills/demotion-proposals/:id/approve': { response: reviewDemotionResponseSchema, summary: '降级提案通过' },
  'POST /api/v1/skills/demotion-proposals/:id/reject': { response: reviewDemotionResponseSchema, summary: '降级提案拒绝' },
  'GET /api/v1/skills/proposals': { response: skillProposalListResponseSchema, summary: '技能提案列表' },
  'POST /api/v1/skills/proposals/scan': { response: scanSkillProposalsResponseSchema, summary: '扫描技能提案' },
  'POST /api/v1/skills/proposals/extract/:executionId': { response: extractSkillProposalResponseSchema, summary: '从执行提取提案' },
  'POST /api/v1/skills/proposals/:id/retract': { response: retractSkillResponseSchema, summary: '撤回提案' },

  // ── specs ──
  'GET /api/v1/specs/:id/changes': { response: specChangeListResponseSchema, summary: 'Spec 变更历史（分页）' },
  'GET /api/v1/specs/:id/changes/stats': { response: changeStatsResponseSchema, summary: '变更统计' },
  'GET /api/v1/specs/changes/:changeId': { response: changeRecordResponseSchema, summary: '变更详情' },
  'POST /api/v1/specs/:id/analyze-change': { response: analyzeChangeResponseSchema, summary: '变更分析（L1-L4 分级）' },
  'POST /api/v1/specs/changes/:changeId/validate': { response: validateChangeResponseSchema, summary: '变更门禁验证' },
  'POST /api/v1/specs/:id/changes/import': { response: importChangesResponseSchema, summary: '变更导入' },
  'GET /api/v1/specs/gates': { response: gatePolicyMapResponseSchema, summary: '门禁策略全表' },
  'GET /api/v1/specs/gates/:level': { response: gatePolicyResponseSchema, summary: '门禁策略（按级别）' },

  // ── triggers / evolution ──
  'GET /api/v1/triggers': { response: listTriggersResponseSchema, summary: '触发器列表' },
  'POST /api/v1/triggers': { response: saveTriggerResponseSchema, summary: '创建触发器' },
  'GET /api/v1/triggers/:id': { response: triggerResponseSchema, summary: '触发器详情' },
  'DELETE /api/v1/triggers/:id': { response: deleteTriggerResponseSchema, summary: '删除触发器' },
  'POST /api/v1/triggers/:id/fire': { response: fireTriggerResponseSchema, summary: '手动触发' },
  'GET /api/v1/triggers/:id/logs': { response: triggerLogsResponseSchema, summary: '触发日志' },
  'GET /api/v1/triggers/costs': { response: triggerCostsResponseSchema, summary: '触发成本' },
  'GET /api/v1/triggers/status': { response: triggerStatusResponseSchema, summary: '调度器状态' },
  'GET /api/v1/evolution/proposals': { response: evolutionProposalListResponseSchema, summary: '进化提案列表' },
  'GET /api/v1/evolution/proposals/:id': { response: evolutionProposalResponseSchema, summary: '进化提案详情' },
  'POST /api/v1/evolution/proposals/:id/approve': { response: evolutionProposalResponseSchema, summary: '进化提案通过' },
  'POST /api/v1/evolution/proposals/:id/reject': { response: evolutionProposalResponseSchema, summary: '进化提案拒绝' },
  'POST /api/v1/evolution/run': { response: evolutionRunResponseSchema, summary: '手动扫描' },

  // ── knowledge（/api/v1/knowledge）──
  'GET /api/v1/knowledge/requirements': { response: requirementDocListResponseSchema, summary: '需求文档知识列表' },
  'POST /api/v1/knowledge/read-file': { response: readKnowledgeFileResponseSchema, summary: '读知识文件' },
  'GET /api/v1/knowledge/file': { response: knowledgeFileResponseSchema, summary: '知识文件详情' },
  'POST /api/v1/knowledge/ask': { response: knowledgeAskResponseSchema, summary: '知识问答' },
  'GET /api/v1/knowledge/gaps': { response: knowledgeGapsResponseSchema, summary: '知识缺口' },
  'GET /api/v1/knowledge/gaps/:type': { response: knowledgeGapStatsResponseSchema, summary: '缺口统计（按类型）' },
  'GET /api/v1/knowledge/unified': { response: unifiedKnowledgeListResponseSchema, summary: '统一知识列表' },
  'POST /api/v1/knowledge/unified': { response: createUnifiedEntryResponseSchema, summary: '创建统一知识条目' },
  'GET /api/v1/knowledge/resolutions': { response: resolutionListResponseSchema, summary: 'Resolution 列表' },
  'GET /api/v1/knowledge/search': { response: knowledgeSearchResponseSchema, summary: '知识搜索' },
  'GET /api/v1/knowledge/resolution/density': { response: resolutionDensityResponseSchema, summary: 'Resolution 密度分' },
  'GET /api/v1/knowledge/resolution/cross-session': { response: crossSessionStatsResponseSchema, summary: '跨会话统计' },
  'POST /api/v1/knowledge/maintenance/run': { response: knowledgeMaintenanceResponseSchema, summary: '手动跑知识维护' },

  // ── knowledge-service ──
  'GET /api/v1/knowledge-service/stats': { response: knowledgeServiceStatsResponseSchema, summary: '知识库统计' },
  'GET /api/v1/knowledge-service/search': { response: knowledgeServiceSearchResponseSchema, summary: '知识库搜索' },
  'GET /api/v1/knowledge-service/entries': { response: knowledgeEntryListResponseSchema, summary: '知识条目列表' },
  'POST /api/v1/knowledge-service/entries': { response: createKnowledgeEntryResponseSchema, summary: '创建知识条目' },
  'GET /api/v1/knowledge-service/entries/:id': { response: knowledgeEntryResponseSchema, summary: '知识条目详情' },
  'PUT /api/v1/knowledge-service/entries/:id': { response: knowledgeEntryResponseSchema, summary: '更新知识条目' },
  'DELETE /api/v1/knowledge-service/entries/:id': { response: knowledgeSuccessResponseSchema, summary: '删除知识条目' },
  'GET /api/v1/knowledge-service/health': { response: knowledgeHealthResponseSchema, summary: '知识健康报告' },
  'GET /api/v1/knowledge-service/flywheel': { response: knowledgeFlywheelResponseSchema, summary: '飞轮指标' },
  'GET /api/v1/knowledge-service/audit': { response: knowledgeAuditResponseSchema, summary: '知识审计报告' },
  'GET /api/v1/knowledge-service/analyst-accuracy': { response: analystAccuracyResponseSchema, summary: '分析准确率' },
  'POST /api/v1/knowledge-service/inject-context': { response: injectContextResponseSchema, summary: '上下文注入' },
  'POST /api/v1/knowledge-service/match-resolutions': { response: matchResolutionsResponseSchema, summary: 'Resolution 匹配' },
  'POST /api/v1/knowledge-service/promote': { response: knowledgeSuccessResponseSchema, summary: '条目晋级（draft → active）' },
  'POST /api/v1/knowledge-service/demote': { response: knowledgeSuccessResponseSchema, summary: '条目降级（draft → archived）' },
  'POST /api/v1/knowledge-service/decay': { response: knowledgeSuccessResponseSchema, summary: '条目衰减' },
  'POST /api/v1/knowledge-service/merge': { response: knowledgeSuccessResponseSchema, summary: '条目合并' },
  'GET /api/v1/knowledge-service/events': { summary: 'SSE 已迁移（301 → /api/v1/events/stream?topics=knowledge）' },

  // ── /api/knowledge 内部（localhost）──
  'GET /api/knowledge/sync-status': { response: knowledgeSyncStatusResponseSchema, summary: '知识同步状态' },
  'POST /api/knowledge/upsert': { response: upsertKnowledgeResponseSchema, summary: '知识 upsert（内部抽取链）' },

  // ── review-proposals / action-center / library / events / transcripts / monitoring ──
  'GET /api/v1/review-proposals/:kind/:id/status': { response: reviewProposalStatusResponseSchema, summary: '提案卡状态' },
  'POST /api/v1/review-proposals/:kind/:id/approve': { response: reviewProposalApproveResponseSchema, summary: '提案卡通过（kind 注册表分发）' },
  'POST /api/v1/review-proposals/:kind/:id/reject': { response: reviewProposalRejectResponseSchema, summary: '提案卡拒绝' },
  'GET /api/v1/action-center': { response: actionCenterResponseSchema, summary: '统一行动中心（stateItems + notifications）' },
  'GET /api/v1/library': { response: libraryListResponseSchema, summary: '阅览室文档列表' },
  'GET /api/v1/library/*splat': { response: libraryDocDetailResponseSchema, summary: '阅览室文档详情' },
  'GET /api/v1/events': { response: eventSearchResponseSchema, summary: '事件搜索（游标壳）' },
  'POST /api/v1/events': { response: createStudioEventResponseSchema, summary: '创建事件' },
  'POST /api/v1/events/agent-events': { response: ingestAgentEventsResponseSchema, summary: 'Agent 事件批量写入' },
  'GET /api/v1/transcripts/:workUnitId': { response: transcriptResponseSchema, summary: 'WU transcript 只读查看' },
  'GET /api/v1/monitoring/agents': { response: agentSummaryResponseSchema, summary: 'Agent 摘要' },
  'GET /api/v1/monitoring/stats': { response: monitoringStatsResponseSchema, summary: '监控统计汇总' },
  'GET /api/v1/monitoring/flywheel': { response: flywheelStatsResponseSchema, summary: '飞轮指标（M1）' },
  'GET /api/v1/monitoring/overhead': { response: overheadStatsResponseSchema, summary: '封装开销（M2）' },
  'GET /api/v1/monitoring/overview': { response: overviewMetricsResponseSchema, summary: '总览指标' },
  'GET /api/v1/monitoring/efficiency': { response: efficiencyMetricsResponseSchema, summary: '效率指标' },

  // ── notifications / notify-channels / outbound-notify ──
  'GET /api/v1/notifications': { response: notificationListResponseSchema, summary: '通知列表' },
  'GET /api/v1/notifications/unread-count': { response: unreadCountResponseSchema, summary: '未读数' },
  'POST /api/v1/notifications/:id/read': { response: notificationReadResponseSchema, summary: '标记已读' },
  'GET /api/v1/notify-channels': { response: notifyChannelsStateResponseSchema, summary: '通知渠道配置状态（脱敏）' },
  'PUT /api/v1/notify-channels/wecom': { response: wecomChannelStateResponseSchema, summary: '配置企微 webhook' },
  'POST /api/v1/notify-channels/wecom/test': { response: notifyChannelsSuccessResponseSchema, summary: '企微渠道测试' },
  'POST /api/v1/notify-channels/clawbot/bind/start': { response: clawbotBindStartResponseSchema, summary: 'ClawBot 扫码绑定发起' },
  'GET /api/v1/notify-channels/clawbot/bind/status': { response: clawbotBindStatusResponseSchema, summary: 'ClawBot 绑定状态' },
  'POST /api/v1/notify-channels/clawbot/unbind': { response: notifyChannelsSuccessResponseSchema, summary: 'ClawBot 解绑' },
  'POST /api/v1/notify-channels/clawbot/test': { response: notifyChannelsSuccessResponseSchema, summary: 'ClawBot 渠道测试' },
  'POST /api/v1/notify/send': { response: notifySendResponseSchema, summary: '出站推送（内部调用）' },

  // ── auth / audit-logs / admin ──
  'GET /api/v1/auth/status': { response: authStatusResponseSchema, summary: '认证状态（含未登录 mode 提示）' },
  'POST /api/v1/auth/login': { response: authResultResponseSchema, summary: '登录' },
  'POST /api/v1/auth/register': { response: authResultResponseSchema, summary: '注册' },
  'POST /api/v1/auth/guest-session': { response: authResultResponseSchema, summary: 'Guest 会话' },
  'GET /api/v1/auth/me': { response: authMeResponseSchema, summary: '当前用户' },
  'POST /api/v1/auth/refresh': { response: authRefreshResponseSchema, summary: '刷新令牌' },
  'POST /api/v1/auth/logout': { response: logoutResponseSchema, summary: '登出' },
  'POST /api/v1/auth/cleanup': { response: cleanupResponseSchema, summary: '过期会话清理' },
  'GET /api/v1/audit-logs': { response: auditLogListResponseSchema, summary: '审计日志（分页）' },
  'GET /api/v1/audit-logs/stats': { response: auditLogStatsResponseSchema, summary: '审计统计' },
  'GET /api/v1/audit-logs/actions': { response: auditLogActionsResponseSchema, summary: '操作类型词表' },
  'GET /api/v1/audit-logs/resources': { response: auditLogResourcesResponseSchema, summary: '资源词表' },
  'GET /api/v1/audit-logs/:id': { response: auditLogGetResponseSchema, summary: '审计详情' },
  'GET /api/v1/admin/docs-freshness': { response: docsFreshnessResponseSchema, summary: '文档新鲜度检查' },

  // ── harness / cso / iron-laws ──
  'GET /api/v1/harness/traces': { response: traceListResponseSchema, summary: '执行轨迹列表' },
  'POST /api/v1/harness/traces': { response: traceRecordResponseSchema, summary: '记录执行轨迹' },
  'GET /api/v1/harness/analysis': { response: traceAnalysisResponseSchema, summary: '轨迹分析' },
  'GET /api/v1/harness/analysis/anomalies': { response: traceAnomaliesResponseSchema, summary: '轨迹异常' },
  'GET /api/v1/harness/constraints': { response: constraintListResponseSchema, summary: '生效约束列表' },
  'GET /api/v1/harness/constraints/stats': { response: constraintStatsResponseSchema, summary: '约束统计' },
  'GET /api/v1/harness/constraints/retired': { response: retiredConstraintListResponseSchema, summary: '已退役约束' },
  'GET /api/v1/harness/constraints/:id': { response: constraintGetResponseSchema, summary: '约束详情' },
  'POST /api/v1/harness/constraints/propose-upgrade': { response: proposeUpgradeResponseSchema, summary: '约束升级提案' },
  'POST /api/v1/harness/constraints/:id/rollback': { response: rollbackConstraintResponseSchema, summary: '约束回滚' },
  'POST /api/v1/harness/check-constraints': { response: checkConstraintsResponseSchema, summary: '约束检查' },
  'POST /api/v1/harness/knowledge/query': { response: harnessKnowledgeQueryResponseSchema, summary: 'harness 知识查询' },
  'GET /api/v1/harness/knowledge': { response: harnessKnowledgeListResponseSchema, summary: 'harness 知识列表' },
  'POST /api/v1/harness/knowledge': { response: harnessKnowledgeSaveResponseSchema, summary: 'harness 知识保存' },
  'GET /api/v1/harness/knowledge/:id': { response: harnessKnowledgeGetResponseSchema, summary: 'harness 知识详情' },
  'DELETE /api/v1/harness/knowledge/:id': { response: harnessKnowledgeDeleteResponseSchema, summary: 'harness 知识删除' },
  'POST /api/v1/harness/knowledge/lint': { response: harnessKnowledgeLintResponseSchema, summary: '知识 lint' },
  'POST /api/v1/harness/estimate-tokens': { response: estimateTokensResponseSchema, summary: 'token 估算' },
  'POST /api/v1/harness/sessions': { response: sessionCreateResponseSchema, summary: '创建会话' },
  'GET /api/v1/harness/sessions/:id': { response: sessionGetResponseSchema, summary: '会话详情' },
  'POST /api/v1/harness/sessions/:id/events': { response: sessionEventResponseSchema, summary: '会话事件写入' },
  'POST /api/v1/harness/sessions/:id/checkpoint': { response: sessionCheckpointResponseSchema, summary: '会话检查点' },
  'GET /api/v1/harness/agents': { response: harnessAgentListResponseSchema, summary: 'Agent 状态列表' },
  'GET /api/v1/harness/agents/:id': { response: harnessAgentStateResponseSchema, summary: 'Agent 状态详情' },
  'POST /api/v1/harness/classify': { response: classifyResponseSchema, summary: '错误分类' },
  'POST /api/v1/harness/failures': { response: failureRecordResponseSchema, summary: '失败记录' },
  'GET /api/v1/harness/health': { response: harnessHealthResponseSchema, summary: 'harness 健康' },
  'GET /api/v1/cso/validate': { response: csoValidateResponseSchema, summary: 'CSO 验证（恒 200 降级三形态）' },
  'GET /api/v1/iron-laws': { response: ironLawListResponseSchema, summary: 'Iron Laws 列表' },
  'GET /api/v1/iron-laws/:id': { response: ironLawGetResponseSchema, summary: 'Iron Law 详情' },
  'POST /api/v1/iron-laws/check': { response: ironLawCheckResponseSchema, summary: '单条检查' },
  'POST /api/v1/iron-laws/check-all': { response: ironLawCheckAllResponseSchema, summary: '全量检查' },

  // ── mcp（REST 管理面；协议面不进文档）──
  'GET /api/v1/mcp/tools': { response: mcpToolListResponseSchema, summary: 'MCP 工具列表' },
  'POST /api/v1/mcp/tools/:name': { response: mcpToolCallResponseSchema, summary: 'MCP 工具调用' },
  'GET /api/v1/mcp/health': { response: mcpHealthResponseSchema, summary: 'MCP 健康（三态；unhealthy 503 裸健康体例外）' },
  'GET /api/v1/mcp/admin/tools': { response: mcpAdminToolListResponseSchema, summary: 'MCP 工具管理列表' },
  'PATCH /api/v1/mcp/admin/tools/:name': { response: mcpToolToggleResponseSchema, summary: 'MCP 工具开关' },
  'GET /api/v1/mcp/admin/stats': { response: mcpAdminStatsResponseSchema, summary: 'MCP 调用统计' },
  'GET /api/v1/mcp/admin/permissions': { response: mcpRolePermissionsResponseSchema, summary: '角色权限表' },
  'PUT /api/v1/mcp/admin/permissions': { response: mcpPermissionSetResponseSchema, summary: '权限设置' },
  'GET /api/v1/mcp/admin/audit': { response: mcpAuditResponseSchema, summary: 'MCP 审计日志' },

  // ── builtin-tools / executions / agents / agent-profiles ──
  'GET /api/v1/builtin-tools': { response: builtinToolListResponseSchema, summary: '内置工具列表' },
  'GET /api/v1/builtin-tools/:name': { response: builtinToolGetResponseSchema, summary: '内置工具详情' },
  'PATCH /api/v1/builtin-tools/:name': { response: builtinToolPatchResponseSchema, summary: '内置工具开关' },
  'GET /api/v1/executions': { response: executionListResponseSchema, summary: '执行列表（LEGACY 面）' },
  'GET /api/v1/executions/:executionId': { response: executionGetResponseSchema, summary: '执行详情（LEGACY 面）' },
  'POST /api/v1/executions/events': { response: executionEventResponseSchema, summary: '执行事件写入（本机限定）' },
  'GET /api/v1/agents': { response: legacyAgentListResponseSchema, summary: 'Agent 列表（LEGACY 面）' },
  'POST /api/v1/agents': { response: legacyAgentResponseSchema, summary: '注册 Agent（LEGACY 面）' },
  'GET /api/v1/agents/:agentId': { response: legacyAgentResponseSchema, summary: 'Agent 详情（LEGACY 面）' },
  'PUT /api/v1/agents/:agentId': { response: legacyAgentResponseSchema, summary: '更新 Agent（LEGACY 面）' },
  'GET /api/v1/agents/:id/token-usage': { response: agentTokenUsageResponseSchema, summary: '角色级 token 视图（§10.5）' },
  'GET /api/v1/agent-profiles': { response: agentProfileListResponseSchema, summary: 'AgentProfile 列表（分页）' },
  'POST /api/v1/agent-profiles': { response: agentProfileResponseSchema, summary: '创建 AgentProfile' },
  'GET /api/v1/agent-profiles/presets': { response: rolePresetListResponseSchema, summary: '角色预设' },
  'GET /api/v1/agent-profiles/:id': { response: agentProfileResponseSchema, summary: 'AgentProfile 详情' },
  'PATCH /api/v1/agent-profiles/:id': { response: agentProfileResponseSchema, summary: '更新 AgentProfile' },
  'GET /api/v1/agent-instances': { response: agentInstanceListResponseSchema, summary: '运行实例列表（分页）' },
  'POST /api/v1/agent-instances': { response: agentInstanceResponseSchema, summary: '创建运行实例' },
  'GET /api/v1/agent-instances/:id': { response: agentInstanceResponseSchema, summary: '运行实例详情' },
  'PATCH /api/v1/agent-instances/:id': { response: agentInstanceResponseSchema, summary: '更新运行实例' },
  'POST /api/v1/agent-instances/:id/terminate': { response: agentInstanceResponseSchema, summary: '终止实例（Admin）' },

  // ── lark / dingtalk health（回调为协议面不进文档）──
  'GET /api/v1/lark/health': { response: larkHealthResponseSchema, summary: '飞书回调健康检查' },
  'GET /api/v1/dingtalk/health': { response: dingtalkHealthResponseSchema, summary: '钉钉回调健康检查' },
};
