/**
 * Workspace Config — manage ~/.studio/workspace.json
 *
 * Auto-generated by `studio daemon start`.
 * Contains workspace identity, server connection, and detected runtimes.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

const STUDIO_DIR = path.join(os.homedir(), '.studio');
const WORKSPACE_FILE = path.join(STUDIO_DIR, 'workspace.json');

export interface WorkspaceConfig {
  /** Display name (default: hostname) */
  name: string;
  /** Studio server URL */
  serverUrl: string;
  /** Machine token for auth */
  token: string;
  /** Detected agent CLI runtimes (provider names) */
  runtimes: string[];
  /** Docker available */
  hasDocker: boolean;
  /** OS platform */
  os: string;
  /** CPU architecture */
  arch: string;
  /** Project root path */
  workspaceRoot: string;
  /** Server-assigned workspace ID (set after registration) */
  workspaceId?: string;
}

/**
 * Generate a workspace config with auto-detected defaults.
 */
export function generateWorkspaceConfig(options: {
  serverUrl: string;
  token: string;
  runtimes: string[];
  hasDocker: boolean;
  workspaceRoot?: string;
  name?: string;
}): WorkspaceConfig {
  return {
    name: options.name || os.hostname(),
    serverUrl: options.serverUrl,
    token: options.token,
    runtimes: options.runtimes,
    hasDocker: options.hasDocker,
    os: os.platform(),
    arch: os.arch(),
    workspaceRoot: options.workspaceRoot || process.cwd(),
  };
}

/**
 * Read existing workspace.json, or null if not found.
 */
export function readWorkspaceConfig(): WorkspaceConfig | null {
  if (!fs.existsSync(WORKSPACE_FILE)) return null;
  try {
    const raw = fs.readFileSync(WORKSPACE_FILE, 'utf-8');
    return JSON.parse(raw) as WorkspaceConfig;
  } catch {
    return null;
  }
}

/**
 * Write workspace.json to disk.
 */
export function writeWorkspaceConfig(config: WorkspaceConfig): void {
  fs.mkdirSync(STUDIO_DIR, { recursive: true });
  fs.writeFileSync(WORKSPACE_FILE, JSON.stringify(config, null, 2) + '\n', 'utf-8');
}

/**
 * Update workspace.json (merge partial updates).
 */
export function updateWorkspaceConfig(updates: Partial<WorkspaceConfig>): WorkspaceConfig {
  const existing = readWorkspaceConfig();
  if (!existing) throw new Error('workspace.json not found. Run `studio daemon start` first.');
  const merged = { ...existing, ...updates };
  writeWorkspaceConfig(merged);
  return merged;
}

/**
 * Get the workspace.json file path.
 */
export function getWorkspaceFilePath(): string {
  return WORKSPACE_FILE;
}
